/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "types_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>




THostPort::~THostPort() throw() {
}


void THostPort::__set_ip(const std::string& val) {
  this->ip = val;
}

void THostPort::__set_port(const int32_t val) {
  this->port = val;
}

const char* THostPort::ascii_fingerprint = "EEBC915CE44901401D881E6091423036";
const uint8_t THostPort::binary_fingerprint[16] = {0xEE,0xBC,0x91,0x5C,0xE4,0x49,0x01,0x40,0x1D,0x88,0x1E,0x60,0x91,0x42,0x30,0x36};

uint32_t THostPort::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->ip);
          this->__isset.ip = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->port);
          this->__isset.port = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t THostPort::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  oprot->incrementRecursionDepth();
  xfer += oprot->writeStructBegin("THostPort");

  xfer += oprot->writeFieldBegin("ip", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->ip);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("port", ::apache::thrift::protocol::T_I32, 2);
  xfer += oprot->writeI32(this->port);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  oprot->decrementRecursionDepth();
  return xfer;
}

void swap(THostPort &a, THostPort &b) {
  using ::std::swap;
  swap(a.ip, b.ip);
  swap(a.port, b.port);
  swap(a.__isset, b.__isset);
}

THostPort::THostPort(const THostPort& other0) {
  ip = other0.ip;
  port = other0.port;
  __isset = other0.__isset;
}
THostPort& THostPort::operator=(const THostPort& other1) {
  ip = other1.ip;
  port = other1.port;
  __isset = other1.__isset;
  return *this;
}
std::ostream& operator<<(std::ostream& out, const THostPort& obj) {
  using apache::thrift::to_string;
  out << "THostPort(";
  out << "ip=" << to_string(obj.ip);
  out << ", " << "port=" << to_string(obj.port);
  out << ")";
  return out;
}


QueryInput::~QueryInput() throw() {
}


void QueryInput::__set_tags(const std::vector<std::string> & val) {
  this->tags = val;
__isset.tags = true;
}

void QueryInput::__set_input(const std::vector<std::string> & val) {
  this->input = val;
}

void QueryInput::__set_type(const std::string& val) {
  this->type = val;
}

const char* QueryInput::ascii_fingerprint = "7DB8B3BD937696C6F449520C758267AA";
const uint8_t QueryInput::binary_fingerprint[16] = {0x7D,0xB8,0xB3,0xBD,0x93,0x76,0x96,0xC6,0xF4,0x49,0x52,0x0C,0x75,0x82,0x67,0xAA};

uint32_t QueryInput::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->tags.clear();
            uint32_t _size2;
            ::apache::thrift::protocol::TType _etype5;
            xfer += iprot->readListBegin(_etype5, _size2);
            this->tags.resize(_size2);
            uint32_t _i6;
            for (_i6 = 0; _i6 < _size2; ++_i6)
            {
              xfer += iprot->readString(this->tags[_i6]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.tags = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->input.clear();
            uint32_t _size7;
            ::apache::thrift::protocol::TType _etype10;
            xfer += iprot->readListBegin(_etype10, _size7);
            this->input.resize(_size7);
            uint32_t _i11;
            for (_i11 = 0; _i11 < _size7; ++_i11)
            {
              xfer += iprot->readBinary(this->input[_i11]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.input = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->type);
          this->__isset.type = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t QueryInput::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  oprot->incrementRecursionDepth();
  xfer += oprot->writeStructBegin("QueryInput");

  if (this->__isset.tags) {
    xfer += oprot->writeFieldBegin("tags", ::apache::thrift::protocol::T_LIST, 1);
    {
      xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->tags.size()));
      std::vector<std::string> ::const_iterator _iter12;
      for (_iter12 = this->tags.begin(); _iter12 != this->tags.end(); ++_iter12)
      {
        xfer += oprot->writeString((*_iter12));
      }
      xfer += oprot->writeListEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldBegin("input", ::apache::thrift::protocol::T_LIST, 2);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->input.size()));
    std::vector<std::string> ::const_iterator _iter13;
    for (_iter13 = this->input.begin(); _iter13 != this->input.end(); ++_iter13)
    {
      xfer += oprot->writeBinary((*_iter13));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("type", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->type);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  oprot->decrementRecursionDepth();
  return xfer;
}

void swap(QueryInput &a, QueryInput &b) {
  using ::std::swap;
  swap(a.tags, b.tags);
  swap(a.input, b.input);
  swap(a.type, b.type);
  swap(a.__isset, b.__isset);
}

QueryInput::QueryInput(const QueryInput& other14) {
  tags = other14.tags;
  input = other14.input;
  type = other14.type;
  __isset = other14.__isset;
}
QueryInput& QueryInput::operator=(const QueryInput& other15) {
  tags = other15.tags;
  input = other15.input;
  type = other15.type;
  __isset = other15.__isset;
  return *this;
}
std::ostream& operator<<(std::ostream& out, const QueryInput& obj) {
  using apache::thrift::to_string;
  out << "QueryInput(";
  out << "tags="; (obj.__isset.tags ? (out << to_string(obj.tags)) : (out << "<null>"));
  out << ", " << "input=" << to_string(obj.input);
  out << ", " << "type=" << to_string(obj.type);
  out << ")";
  return out;
}


QuerySpec::~QuerySpec() throw() {
}


void QuerySpec::__set_name(const std::string& val) {
  this->name = val;
__isset.name = true;
}

void QuerySpec::__set_inputset(const std::vector<QueryInput> & val) {
  this->inputset = val;
}

const char* QuerySpec::ascii_fingerprint = "4B668F562C1E4C7FAC24FC6C66C474C4";
const uint8_t QuerySpec::binary_fingerprint[16] = {0x4B,0x66,0x8F,0x56,0x2C,0x1E,0x4C,0x7F,0xAC,0x24,0xFC,0x6C,0x66,0xC4,0x74,0xC4};

uint32_t QuerySpec::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          this->__isset.name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->inputset.clear();
            uint32_t _size16;
            ::apache::thrift::protocol::TType _etype19;
            xfer += iprot->readListBegin(_etype19, _size16);
            this->inputset.resize(_size16);
            uint32_t _i20;
            for (_i20 = 0; _i20 < _size16; ++_i20)
            {
              xfer += this->inputset[_i20].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.inputset = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t QuerySpec::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  oprot->incrementRecursionDepth();
  xfer += oprot->writeStructBegin("QuerySpec");

  if (this->__isset.name) {
    xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 1);
    xfer += oprot->writeString(this->name);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldBegin("inputset", ::apache::thrift::protocol::T_LIST, 2);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->inputset.size()));
    std::vector<QueryInput> ::const_iterator _iter21;
    for (_iter21 = this->inputset.begin(); _iter21 != this->inputset.end(); ++_iter21)
    {
      xfer += (*_iter21).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  oprot->decrementRecursionDepth();
  return xfer;
}

void swap(QuerySpec &a, QuerySpec &b) {
  using ::std::swap;
  swap(a.name, b.name);
  swap(a.inputset, b.inputset);
  swap(a.__isset, b.__isset);
}

QuerySpec::QuerySpec(const QuerySpec& other22) {
  name = other22.name;
  inputset = other22.inputset;
  __isset = other22.__isset;
}
QuerySpec& QuerySpec::operator=(const QuerySpec& other23) {
  name = other23.name;
  inputset = other23.inputset;
  __isset = other23.__isset;
  return *this;
}
std::ostream& operator<<(std::ostream& out, const QuerySpec& obj) {
  using apache::thrift::to_string;
  out << "QuerySpec(";
  out << "name="; (obj.__isset.name ? (out << to_string(obj.name)) : (out << "<null>"));
  out << ", " << "inputset=" << to_string(obj.inputset);
  out << ")";
  return out;
}


RegMessage::~RegMessage() throw() {
}


void RegMessage::__set_app_name(const std::string& val) {
  this->app_name = val;
}

void RegMessage::__set_endpoint(const THostPort& val) {
  this->endpoint = val;
}

const char* RegMessage::ascii_fingerprint = "8A6FE535189D3403D9FD6C98A103F76F";
const uint8_t RegMessage::binary_fingerprint[16] = {0x8A,0x6F,0xE5,0x35,0x18,0x9D,0x34,0x03,0xD9,0xFD,0x6C,0x98,0xA1,0x03,0xF7,0x6F};

uint32_t RegMessage::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->app_name);
          this->__isset.app_name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->endpoint.read(iprot);
          this->__isset.endpoint = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t RegMessage::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  oprot->incrementRecursionDepth();
  xfer += oprot->writeStructBegin("RegMessage");

  xfer += oprot->writeFieldBegin("app_name", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->app_name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("endpoint", ::apache::thrift::protocol::T_STRUCT, 2);
  xfer += this->endpoint.write(oprot);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  oprot->decrementRecursionDepth();
  return xfer;
}

void swap(RegMessage &a, RegMessage &b) {
  using ::std::swap;
  swap(a.app_name, b.app_name);
  swap(a.endpoint, b.endpoint);
  swap(a.__isset, b.__isset);
}

RegMessage::RegMessage(const RegMessage& other24) {
  app_name = other24.app_name;
  endpoint = other24.endpoint;
  __isset = other24.__isset;
}
RegMessage& RegMessage::operator=(const RegMessage& other25) {
  app_name = other25.app_name;
  endpoint = other25.endpoint;
  __isset = other25.__isset;
  return *this;
}
std::ostream& operator<<(std::ostream& out, const RegMessage& obj) {
  using apache::thrift::to_string;
  out << "RegMessage(";
  out << "app_name=" << to_string(obj.app_name);
  out << ", " << "endpoint=" << to_string(obj.endpoint);
  out << ")";
  return out;
}


LatencyStat::~LatencyStat() throw() {
}


void LatencyStat::__set_hostport(const THostPort& val) {
  this->hostport = val;
}

void LatencyStat::__set_latency(const int64_t val) {
  this->latency = val;
}

const char* LatencyStat::ascii_fingerprint = "09E70C4FB217E12F46E0B39A783252CC";
const uint8_t LatencyStat::binary_fingerprint[16] = {0x09,0xE7,0x0C,0x4F,0xB2,0x17,0xE1,0x2F,0x46,0xE0,0xB3,0x9A,0x78,0x32,0x52,0xCC};

uint32_t LatencyStat::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->hostport.read(iprot);
          this->__isset.hostport = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->latency);
          this->__isset.latency = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t LatencyStat::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  oprot->incrementRecursionDepth();
  xfer += oprot->writeStructBegin("LatencyStat");

  xfer += oprot->writeFieldBegin("hostport", ::apache::thrift::protocol::T_STRUCT, 1);
  xfer += this->hostport.write(oprot);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("latency", ::apache::thrift::protocol::T_I64, 2);
  xfer += oprot->writeI64(this->latency);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  oprot->decrementRecursionDepth();
  return xfer;
}

void swap(LatencyStat &a, LatencyStat &b) {
  using ::std::swap;
  swap(a.hostport, b.hostport);
  swap(a.latency, b.latency);
  swap(a.__isset, b.__isset);
}

LatencyStat::LatencyStat(const LatencyStat& other26) {
  hostport = other26.hostport;
  latency = other26.latency;
  __isset = other26.__isset;
}
LatencyStat& LatencyStat::operator=(const LatencyStat& other27) {
  hostport = other27.hostport;
  latency = other27.latency;
  __isset = other27.__isset;
  return *this;
}
std::ostream& operator<<(std::ostream& out, const LatencyStat& obj) {
  using apache::thrift::to_string;
  out << "LatencyStat(";
  out << "hostport=" << to_string(obj.hostport);
  out << ", " << "latency=" << to_string(obj.latency);
  out << ")";
  return out;
}


