/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.umich.clarity.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2015-6-24")
public class LatencyStat implements org.apache.thrift.TBase<LatencyStat, LatencyStat._Fields>, java.io.Serializable, Cloneable, Comparable<LatencyStat> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("LatencyStat");

  private static final org.apache.thrift.protocol.TField HOSTPORT_FIELD_DESC = new org.apache.thrift.protocol.TField("hostport", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField LATENCY_FIELD_DESC = new org.apache.thrift.protocol.TField("latency", org.apache.thrift.protocol.TType.I64, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new LatencyStatStandardSchemeFactory());
    schemes.put(TupleScheme.class, new LatencyStatTupleSchemeFactory());
  }

  public THostPort hostport; // required
  public long latency; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    HOSTPORT((short)1, "hostport"),
    LATENCY((short)2, "latency");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // HOSTPORT
          return HOSTPORT;
        case 2: // LATENCY
          return LATENCY;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __LATENCY_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.HOSTPORT, new org.apache.thrift.meta_data.FieldMetaData("hostport", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, THostPort.class)));
    tmpMap.put(_Fields.LATENCY, new org.apache.thrift.meta_data.FieldMetaData("latency", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(LatencyStat.class, metaDataMap);
  }

  public LatencyStat() {
  }

  public LatencyStat(
    THostPort hostport,
    long latency)
  {
    this();
    this.hostport = hostport;
    this.latency = latency;
    setLatencyIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public LatencyStat(LatencyStat other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetHostport()) {
      this.hostport = new THostPort(other.hostport);
    }
    this.latency = other.latency;
  }

  public LatencyStat deepCopy() {
    return new LatencyStat(this);
  }

  @Override
  public void clear() {
    this.hostport = null;
    setLatencyIsSet(false);
    this.latency = 0;
  }

  public THostPort getHostport() {
    return this.hostport;
  }

  public LatencyStat setHostport(THostPort hostport) {
    this.hostport = hostport;
    return this;
  }

  public void unsetHostport() {
    this.hostport = null;
  }

  /** Returns true if field hostport is set (has been assigned a value) and false otherwise */
  public boolean isSetHostport() {
    return this.hostport != null;
  }

  public void setHostportIsSet(boolean value) {
    if (!value) {
      this.hostport = null;
    }
  }

  public long getLatency() {
    return this.latency;
  }

  public LatencyStat setLatency(long latency) {
    this.latency = latency;
    setLatencyIsSet(true);
    return this;
  }

  public void unsetLatency() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __LATENCY_ISSET_ID);
  }

  /** Returns true if field latency is set (has been assigned a value) and false otherwise */
  public boolean isSetLatency() {
    return EncodingUtils.testBit(__isset_bitfield, __LATENCY_ISSET_ID);
  }

  public void setLatencyIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __LATENCY_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case HOSTPORT:
      if (value == null) {
        unsetHostport();
      } else {
        setHostport((THostPort)value);
      }
      break;

    case LATENCY:
      if (value == null) {
        unsetLatency();
      } else {
        setLatency((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case HOSTPORT:
      return getHostport();

    case LATENCY:
      return Long.valueOf(getLatency());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case HOSTPORT:
      return isSetHostport();
    case LATENCY:
      return isSetLatency();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof LatencyStat)
      return this.equals((LatencyStat)that);
    return false;
  }

  public boolean equals(LatencyStat that) {
    if (that == null)
      return false;

    boolean this_present_hostport = true && this.isSetHostport();
    boolean that_present_hostport = true && that.isSetHostport();
    if (this_present_hostport || that_present_hostport) {
      if (!(this_present_hostport && that_present_hostport))
        return false;
      if (!this.hostport.equals(that.hostport))
        return false;
    }

    boolean this_present_latency = true;
    boolean that_present_latency = true;
    if (this_present_latency || that_present_latency) {
      if (!(this_present_latency && that_present_latency))
        return false;
      if (this.latency != that.latency)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_hostport = true && (isSetHostport());
    list.add(present_hostport);
    if (present_hostport)
      list.add(hostport);

    boolean present_latency = true;
    list.add(present_latency);
    if (present_latency)
      list.add(latency);

    return list.hashCode();
  }

  @Override
  public int compareTo(LatencyStat other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetHostport()).compareTo(other.isSetHostport());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHostport()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.hostport, other.hostport);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLatency()).compareTo(other.isSetLatency());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLatency()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.latency, other.latency);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("LatencyStat(");
    boolean first = true;

    sb.append("hostport:");
    if (this.hostport == null) {
      sb.append("null");
    } else {
      sb.append(this.hostport);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("latency:");
    sb.append(this.latency);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (hostport != null) {
      hostport.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class LatencyStatStandardSchemeFactory implements SchemeFactory {
    public LatencyStatStandardScheme getScheme() {
      return new LatencyStatStandardScheme();
    }
  }

  private static class LatencyStatStandardScheme extends StandardScheme<LatencyStat> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, LatencyStat struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // HOSTPORT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.hostport = new THostPort();
              struct.hostport.read(iprot);
              struct.setHostportIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // LATENCY
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.latency = iprot.readI64();
              struct.setLatencyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, LatencyStat struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.hostport != null) {
        oprot.writeFieldBegin(HOSTPORT_FIELD_DESC);
        struct.hostport.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(LATENCY_FIELD_DESC);
      oprot.writeI64(struct.latency);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class LatencyStatTupleSchemeFactory implements SchemeFactory {
    public LatencyStatTupleScheme getScheme() {
      return new LatencyStatTupleScheme();
    }
  }

  private static class LatencyStatTupleScheme extends TupleScheme<LatencyStat> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, LatencyStat struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetHostport()) {
        optionals.set(0);
      }
      if (struct.isSetLatency()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetHostport()) {
        struct.hostport.write(oprot);
      }
      if (struct.isSetLatency()) {
        oprot.writeI64(struct.latency);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, LatencyStat struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.hostport = new THostPort();
        struct.hostport.read(iprot);
        struct.setHostportIsSet(true);
      }
      if (incoming.get(1)) {
        struct.latency = iprot.readI64();
        struct.setLatencyIsSet(true);
      }
    }
  }

}

